name: Build
on: [push]
jobs:
  ci:
    env:
      OS: ubuntu-latest
      PYTHON: '3.10.9'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: poetry install
      - name: Tests
        run: poetry run pytest -v
      - name: Coverage
        run: poetry run coverage run --branch -m pytest
      - name: Coverage report
        run: poetry run coverage xml
      - uses: codecov/codecov-action@v3
        with:
          name: codecov-2048
          directory: ./coverage/reports/
          files: ./coverage.xml
          env_vars: OS,PYTHON
          flags: unittests
          fail_ci_if_error: true
          verbose: true
